allowed_actions:
- open_app
- close_app
- set_volume
- mute_volume
- play_pause_media
- next_track
- prev_track
- search_file
- open_url
- type_text
- take_screenshot
- show_time
- show_battery
app_aliases:
  calculator: calc
  chrome: chrome
  discord: discord://
  explorer: explorer
  firefox: firefox
  notepad: notepad
  paint: mspaint
  spotify: 'spotify:'
  steam: steam://open/main
  vs code: code
  vscode: code
chunk_duration: 2.0
language: en
mic_device: 3
ollama_model: qwen2.5:3b
ollama_url: http://localhost:11434
output_device: 29
piper_path: piper/piper/piper.exe
search_dirs:
- ~/Documents
- ~/Downloads
- ~/Desktop
silence_duration: 1.5
silence_threshold: 0.01
tts_enabled: true
voice_model: voices/en_US-ryan-high.onnx
wake_word: vox
whisper_compute_type: int8
whisper_device: cpu
whisper_model: base
