allowed_actions:
- open_app
- close_app
- set_volume
- mute_volume
- play_pause_media
- next_track
- prev_track
- search_file
- open_url
- type_text
- take_screenshot
- show_time
- show_battery
app_aliases:
  discord: 'discord://'
  spotify: 'spotify:'
  steam: 'steam://open/main'
  chrome: chrome
  firefox: firefox
  vscode: code
  vs code: code
  notepad: notepad
  calculator: calc
  explorer: explorer
  paint: mspaint
hotkey: alt
language: en
mic_device: 3
ollama_model: qwen2.5:3b
ollama_url: http://localhost:11434
output_device: 29
piper_path: ../piper/piper/piper.exe
search_dirs:
- ~/Documents
- ~/Downloads
- ~/Desktop
tts_enabled: true
voice_model: ../voices/en_US-ryan-high.onnx
whisper_compute_type: int8
whisper_device: cpu
whisper_model: base
